"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def evenadd(a, b):
    if b % 2 == 0:
        return a + b
    return a

def prob2():
    fibo = [1, 1]
    top = 1
    while top <= 4000000:
        fibo.append(fibo[-1] + fibo[-2])
        top = fibo[-1]
    return reduce(evenadd, fibo[2:])

print prob2()