"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
import timeit

def divisors(n):
    divisors = set([])
    cap = n
    i = 1
    while i <= cap:
        if n % i == 0:
            divisors.add(i)
            divisors.add(n/i)
        i += 1
        cap = n/i + 1
    return divisors

def triangles2(ceil):
    triangles = [1]
    i = 1
    while 1:
        new = triangles[-1] + i+1
        triangles.append(new)
        if new >= ceil:
            return triangles
        i += 1

def prob12(a):
    triangles = triangles2(a)
    if len(a) < 501:
        return len(a)
    for n in triangles[-1:-100:-1]:
        a = divisors(n)
        if len(a) >= 501:
            print n, len(a)
        if len(a) == 501:
            return divisors(n)

def fac(n):
    if n <= 1:
        return 1
    return n*fac(n-1)

def facs(ceil):
    facs = set([1])
    for i in range(1, 100):
        new = fac(i)
        facs.add(new)
        if new >= ceil:
            return facs

def test():
    triangles = triangles2(1000)
    for n in triangles:
        print len(divisors(n)), n

print test()


